const memeTitles = [
    "The Lusty Argonian Maid",
    "fanfiction.net",
    "Dirk Strider Beats the Shit out of Kylo Ren and Leaves",
    "Toilet-Bound Hanako-kun: Volume 2",
    "My Immortal",
    "I made a cocktail and it's so stinky... I'm no mixologist",
    "Homestuck",
    "Harry Potter and the Death of the Transphobe",
    "Trans Wizard Harriet Porber and the Bad Boy Parasaurolophus",
    "Harry Potter and the Cursed Child",
    "The Forbidden Days of McPhantom",
    "How Bad Do You Want It",
    "All My Friends Are Dead",
    "Go the Fuck to Sleep",
    "Breadfish",
    "Mein Kampf",
    "Extreme Pokemon: The Guide for the Ultimate Fam",
];

const ficTitles = [
    "Mortified",
    "Just Fourteen",
    "Eidolon Interloper",
    "Talent Night",
    "Smells like Team Spirit",
    "Eidolon",
    "Shift",
    "A Thermos for Valerie",
    "An Unlikely Alliance",
    "Captive Audience",
    "Pits",
    "Real Life",
    "Spirit of Protection",
    "A Snapping Sound",
    "Diamonds in the Rough",
    "Spite Is a Perfectly Good Motivation to Survive a Zombie Apocalypse",
    "My Immortal",
    "Dante's Inferno",
    "Paradise Lost",
    "Beneath the Depths",
    "Treading Water",
    "The Divine Champion",
    "Electric Veins",
    "Yesterday Upon the Stair",
    "Can I Not Grasp Them with a Tighter Clasp?",
    "Mirror, Mirror",
    "Heavy Silences",
    "Reconciliation",
    "Insomnia",
    "Sierra WinterBreeze",
    "Jersey Boy",
]

const realBookTitles = [
    'Pride and Prejudice',
    'Lord of the Flies',
    'Grapes of Wrath',
    "The Illiad",
    "The Odyssey",
    "The Aeneid",
    "Dante's Inferno",
    "Beowulf",
    'By the Illiad and the Odyssey',
    'Gift of the Magi',
    'The Cask of Amontillado',
    'Sisterhood of Traveling Pants',
    'The Great Gatsby',
    'The Most Dangerous Game',
    'Romeo and Juliet',
    'Fullmetal Alchemist',
    'Working Stiff',
    "Stiff",
    "Antigone",
    "Frankenstein",
    "Warriors: Into the Wild",
    "Jekyll and Hyde",
    "Invisible Man",
    "Hard Times",
    "A Tale of Two Cities",
    "The Count of Monte Cristo",
    "Hypnosis for Dummies",
    "Eats, Shoots, and Leaves",
    "Twin Feathers",
    "Harry Potter",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half-Blood Prince",
    "Oedipus Rex",
    "Iphigenia",
    "Paradise Lost",
    "Dracula",
    "Don Quixote",
    "Jekyll and Mister Hyde",
    "Shadow over Innsmouth",
    "The Pit and the Pendulum",
    "The Mask of Red Death",
    "The Tell-tale Heart",
    "A Christmas Carol",
    "1984",
    "All Quiet On the Western Front",
    "Stranger in a Strange Land",
    "First King of Shannara",
    "The Sword of Shannara",
    "The Elfstones of Shannara",
    "The Wishsong of Shannara",
    "The Scions of Shannara",
    "The Druid of Shannara",
    "The Elf Queen of Shannara",
    "The Tailsmans of Shannara",
    "Ilse Witch",
    "Antrax",
    "Morgawr",
    "Jarka Ruus",
    "Tanequil",
    "Straken",
    "Carrie",
    "Salem's Lot",
    "The Shining",
    "Rage",
    "The Stand",
    "The Long Walk",
    "The Dead Zone",
    "Firestarter",
    "Roadwork",
    "Cujo",
    "The Running Man",
    "The Dark Tower: The Gunslinger",
    "Christine",
    "Pet Sematary", 
    "Let The Right One In",
    "A Little Life",
    "Twilight",
    "Breaking Dawn",
    "Eclipse",
    "New Moon",
    "Haunted Halls",
    "A Wrinkle in Time",
    "Pendragon: Black Water",
    "Pendragon: The Rivers of Zadaa",
    "The Return of the King",
    "Pendragon: The Merchant of Death",
    "A Wind in the Door",
    "A Splatoon Graphic Novel?",
    "Overlord",
    "Pendragon: Raven Rise",
    "The Poisonwood Bible",
    "Hoot",
    "Pendragon: The Quillan Games",
    "Shiloh",
    "Saving Shiloh",
    "Shiloh Season",
    "Tithe",
    "The Looking Glass Wars",
    "Pendragon: The Pilgrims of Rayne",
    "Pendragon: The Soldiers of Halla",
    "Memoirs of a Geisha",
    "Holes",
    "Journey to the West",
    "From Elvish to Klingon",
    "Ophelia",
    "Bhagavad Gita",
    "Just Ella",
    "The Crystal Keeper",
    "The Power of Fire",
    "Eclipse",
    "Evermore",
    "Night Star",
    "Emily Windsnap and the Monster from the Deep",
    "Emily Windsnap and the Castle in the Mist",
    "Teenage Mermaid",
    "Rani in the Mermaid Lagoon",
    "Nintendo Games Secrets",
    "Replica: Virtual Amy",
    "The Lion, the Witch, and the Wardrobe",
    "The Horse and His Boy",
    "Prince Caspian",
    "The Voyage of the Dawn Treader",
    "The Last Battle",
    "Things Fall Apart",
    "Little Women",
    "Anne of Green Gables",
    "Esperanza Rising",
    "Hamlet",
    "Uglies",
    "Pretties",
    "Specials",
    "Extras",
    "The Prince and the Pauper",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "Sarah Plain and Tall",
    "Cricket in Times Square",
    "The Little Mermaid",
    "The Boxcar Children",
    "Charlotte's Web",
    "Beauty and the Beast",
    "Death of a Salesman",
    "Pygmalion",
    "A Doll's House",
    "Catch-22",
    "Fahrenheit 451",
    "Animal Farm",
    "1984",
    "To Kill a Mockingbird",
    "Lord of the Flies",
    "Brave New World",
    "The Catcher in the Rye",
    "Hunger Games",
    "Wuthering Heights",
    "Lolita",
    "The Zelda Encylopedia",
    "Hyrule Historia",
    "The Very Hungry Caterpiller",
    "Slugs and Love",
    "Little House in the Big Woods",
    "Elmer and the Dragon",
    "The Dragon's Blueland",
    "The Courage of Sarah Noble",
    "The Hobbit",
    "The Fellowship of the Ring",
    "The Two Towers",
    "The Return of the King",
    "The Communist Manifesto",
    "Little House on the Prairie",
    "The Jungle Book",
    "The Little Prince",
    "Robin Hood",
    "Wizard of Oz",
    "The Secret Garden",
    "Where the Red Fern Grows",
    "Bridge to Terabithia",
    "Inkheart",
    "Inkspell",
    "Inkdeath",
    "Treasure Island",
    "A Christmas Carol",
    "Tom Sawyer",
    "The Call of the Wild",
    "The Strange Case of Dr. Jekyll and Mr. Hyde",
    "Julius Caesar",
    "Adventures of Huckleberry Finn",
    "Othello",
    "Pride and Prejudice",
    "Esperanto",
    "Extreme Pokemon: The Guide for the Ultimate Fan",
    "Kingdom Keepers",
];


// gets a random book title. 1% chance of a *meme* title, 9% chance of a fanfic, 90% chance of a real title
const getBookTitle = () => {
    const listSelector = Math.floor(Math.random() * 100);
    let list = [];
    if(listSelector <= 1){
        list = memeTitles;
    } else if(listSelector <= 10){
        list = ficTitles;
    } else {
        list = realBookTitles;
    }


    const index = Math.floor(Math.random() * list.length);
    return list[index];
}


module.exports = {
    bookTitles: [...memeTitles, ...ficTitles, ...realBookTitles],
    getBookTitle
}