
const bookTitles = [
    'Pride and Prejudice',
    'Lord of the Flies',
    'Grapes of Wrath',
    "The Illiad",
    "The Odyssey",
    "The Aeneid",
    "Dante's Inferno",
    "Beowulf",
    'By the Illiad and the Odyssey',
    'Gift of the Magi',
    'The Cask of Amontillado',
    'Sisterhood of Traveling Pants',
    'The Great Gatsby',
    'The Most Dangerous Game',
    'Romeo and Julliet',
    'Fullmetal Alchemist',
    'Working Stiff',
    "Stiff",
    "Antigone",
    "Frankenstein",
    "A tale of two cities",
    "Warriors: Into the Wild",
    "Jekyll and Hyde",
    "Invisible Man",
    "All My Friends Are Dead",
    "Go the Fuck to Sleep",
    "Hard Times",
    "A Tale of Two Cities",
    "Toilet-Bound Hanako-kun: Volume 2",
    "The Count of Monte Cristo",
    "Homestuck",
    "Hypnosis for Dummies",
    "The Lusty Argonian Maid",
    "fanfiction.net",
    "Dirk Strider Beats the Shit out of Kylo Ren and Leaves",
    "Eats, Shoots, and Leaves",
    "Twin Feathers",
    "Harry Potter",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half-Blood Prince",
    "Oedipus Rex",
    "Iphigenia",
    "Paradise Lost",
    "Dracula",
    "Don Quixote",
    "Jekyll and Mister Hyde",
    "Shadow over Innsmouth",
    "The Pit and the Pendulum",
    "The Mask of Red Death",
    "The Tell-tale Heart",
    "A Christmas Carol",
    "1984",
    "All Quiet On the Western Front",
    "Stranger in a Strange Land",
    "First King of Shannara",
    "The Sword of Shannara",
    "The Elfstones of Shannara",
    "The Wishsong of Shannara",
    "The Scions of Shannara",
    "The Druid of Shannara",
    "The Elf Queen of Shannara",
    "The Tailsmans of Shannara",
    "Ilse Witch",
    "Antrax",
    "Morgawr",
    "Jarka Ruus",
    "Tanequil",
    "Straken",
    "Mortified",
    "Just Fourteen",
    "Eidolon Interloper",
    "Talent Night",
    "Smells like Team Spirit",
    "Eidolon",
    "Carrie",
    "Salem's Lot",
    "The Shining",
    "Rage",
    "The Stand",
    "The Long Walk",
    "The Dead Zone",
    "Firestarter",
    "Roadwork",
    "Cujo",
    "The Running Man",
    "The Dark Tower: The Gunslinger",
    "Christine",
    "Pet Sematary", 
    "Let The Right One In",
    "A Little Life"
];


module.exports = {
    bookTitles: bookTitles
}